name: servicelocator_get_it
description: Dependency injection library implementation
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.4.0
  servicelocator:
    path: ../../.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^0.2.0
